/**
 * The bundled third-party licence data, loaded on demand.
 *
 * `src/generated/third-party-licences.json` is half a megabyte: every package
 * that ships inside the app, plus the full text of every distinct licence among
 * them. Nothing may import it at module scope. An import there would be resolved
 * while the app is starting — read, parsed and then held for the whole session —
 * to serve a screen most people never open.
 *
 * So the ONLY reference to that file anywhere in the app is inside the function
 * below, which a screen calls from an effect. Metro resolves a module reference
 * inside a function body when the call runs, not when the module is evaluated,
 * which is the property that matters here.
 *
 * The file is generated by `scripts/generate-third-party-licenses.mjs` alongside
 * `THIRD_PARTY_LICENSES.md`; `npm run licences:check` fails when either has
 * drifted from the dependency tree.
 */

export interface LicencePackage {
  name: string
  version: string
  /** The identifier the package declares. Empty when it declares none at all. */
  licence: string
  repository?: string
  /** Key into `texts`. Absent when the package ships no licence file of its own. */
  text?: string
}

export interface LicenceData {
  generatedBy: string
  scope: string
  /** Workspace packages left out of the list, because they are this repository's code. */
  excludesWorkspacePackages: string[]
  packages: LicencePackage[]
  /** Licence text by content hash: identical texts are stored once. */
  texts: Record<string, string>
}

/**
 * Read the bundled data. The result is a promise because the caller is a screen
 * with a loading state and an error state, and because that is the shape a real
 * asynchronous load would have if this ever becomes one.
 *
 * `require` rather than `import()`, deliberately: Metro defers both until the
 * call runs, so laziness is not what separates them — but the app's Jest
 * environment is CommonJS without `--experimental-vm-modules`, where a dynamic
 * import throws outright. A screen that could not be tested at all would be the
 * worse trade. `src/polyfills.ts` takes the same route for the same kind of
 * reason.
 *
 * The shape is guaranteed by the generator that writes the file, not by the type
 * checker; asserting through `unknown` keeps half a megabyte of JSON literal out
 * of the project's inferred types.
 */
export async function loadLicenceData(): Promise<LicenceData> {
  const loaded: unknown = require('../../generated/third-party-licences.json')

  return loaded as LicenceData
}
