/**
 * Regenerates the golden corpus under `contract/`, or checks that it is current.
 *
 *   npm run golden          # rewrite every generated file under contract/
 *   npm run golden:check    # regenerate into a temp dir; fail if contract/ differs
 *
 * Everything is generated into a scratch directory first, so a failed step
 * never leaves contract/ half-written and `--check` never touches it at all.
 *
 * Generated (owned by this script, replaced wholesale):
 *   contract/transcript/golden/*.json      the recorded engine calls
 *   contract/transcript/golden-summary.json  counts per operation
 *   contract/transcript/fixtures/*.json    the engine's test fixtures
 *   contract/transcript/streams/*.json     fake-gateway scenarios
 *   contract/gateway/vectors/*.json        gateway-client pure functions
 *   contract/markdown/*.json               the Expo app's Markdown block structure
 *   the counts section of contract/README.md
 * Hand-written (never touched): the rest of contract/README.md, contract/push/.
 */
import { spawnSync } from 'node:child_process'
import {
  cpSync,
  existsSync,
  mkdirSync,
  mkdtempSync,
  readdirSync,
  readFileSync,
  rmSync,
  statSync,
  writeFileSync
} from 'node:fs'
import { tmpdir } from 'node:os'
import { join, relative, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

import prettier from 'prettier'

import { prettyJson } from './canonical-json'

const repoRoot = resolve(fileURLToPath(new URL('.', import.meta.url)), '../..')
const contractDir = join(repoRoot, 'contract')
const check = process.argv.includes('--check')

/** Directories and files under contract/ this script owns, relative to it. */
const GENERATED = [
  'transcript/golden',
  'transcript/golden-summary.json',
  'transcript/fixtures',
  'transcript/streams',
  'gateway/vectors',
  'markdown'
]

const COUNTS_START = '<!-- golden:counts:start -->'
const COUNTS_END = '<!-- golden:counts:end -->'

interface OpStats {
  recorded: number
  replayable: number
  skipped: Record<string, number>
  readsClock: boolean
}

function step(label: string, command: string, args: string[], env: Record<string, string> = {}): void {
  const result = spawnSync(command, args, {
    cwd: repoRoot,
    env: { ...process.env, ...env },
    encoding: 'utf8',
    maxBuffer: 64 * 1024 * 1024
  })

  if (result.status !== 0) {
    process.stderr.write(`golden: ${label} failed\n${result.stdout ?? ''}${result.stderr ?? ''}\n`)
    process.exit(1)
  }
}

function aggregate(statsDir: string): Record<string, OpStats> {
  const total: Record<string, OpStats> = {}

  for (const file of readdirSync(statsDir).sort()) {
    const perFile = JSON.parse(readFileSync(join(statsDir, file), 'utf8')) as Record<string, OpStats>

    for (const [op, stats] of Object.entries(perFile)) {
      const entry = (total[op] ??= { recorded: 0, replayable: 0, skipped: {}, readsClock: false })

      entry.recorded += stats.recorded
      entry.replayable += stats.replayable
      entry.readsClock ||= stats.readsClock

      for (const [reason, count] of Object.entries(stats.skipped)) {
        entry.skipped[reason] = (entry.skipped[reason] ?? 0) + count
      }
    }
  }

  return total
}

function filesUnder(dir: string): string[] {
  if (!existsSync(dir)) {
    return []
  }

  return readdirSync(dir, { recursive: true, withFileTypes: true })
    .filter(entry => entry.isFile())
    .map(entry => relative(dir, join(entry.parentPath, entry.name)))
    .sort()
}

/** The files one owned path stands for (itself, or everything under it), relative to `base`. */
function ownedFiles(base: string, owned: string): string[] {
  const path = join(base, owned)

  if (!existsSync(path)) {
    return []
  }

  return statSync(path).isFile() ? [owned] : filesUnder(path).map(file => join(owned, file))
}

function countsSection(
  ops: Record<string, OpStats>,
  streams: number,
  vectors: Record<string, number>,
  markdown: Record<string, number>
): string {
  const names = Object.keys(ops).sort()
  const recorded = names.reduce((sum, op) => sum + (ops[op]?.recorded ?? 0), 0)
  const replayable = names.reduce((sum, op) => sum + (ops[op]?.replayable ?? 0), 0)
  const percent = recorded ? ((replayable / recorded) * 100).toFixed(1) : '0.0'
  const byReason: Record<string, number> = {}
  const markdownCases = Object.values(markdown).reduce((a, b) => a + b, 0)
  const markdownGroups = Object.entries(markdown)
    .map(([file, count]) => `${file.replace(/\.json$/, '')} ${count}`)
    .join(', ')

  for (const op of names) {
    for (const [reason, count] of Object.entries(ops[op]?.skipped ?? {})) {
      byReason[reason] = (byReason[reason] ?? 0) + count
    }
  }

  const lines = [
    COUNTS_START,
    '',
    '_Generated by `npm run golden`; do not edit by hand._',
    '',
    `- Transcript calls recorded: **${recorded}**; replayable and in the corpus: **${replayable}** (${percent} %); skipped: **${recorded - replayable}**.`,
    `- Stream scenarios: **${streams}**. Gateway vector files: **${Object.keys(vectors).length}** with **${Object.values(vectors).reduce((a, b) => a + b, 0)}** vectors.`,
    `- Markdown files: **${Object.keys(markdown).length}** with **${markdownCases}** cases (${markdownGroups}).`,
    ''
  ]

  if (Object.keys(byReason).length) {
    lines.push('Skipped calls by reason:', '', '| reason | calls |', '| --- | --- |')

    for (const reason of Object.keys(byReason).sort()) {
      lines.push(`| ${reason} | ${byReason[reason]} |`)
    }

    lines.push('')
  }

  lines.push(
    'Per operation (`clock` marks an operation that read the clock itself and therefore carries `now` on its calls):',
    '',
    '| op | recorded | replayable | skipped (reason: calls) | clock |',
    '| --- | --- | --- | --- | --- |'
  )

  for (const op of names) {
    const entry = ops[op]!
    const skipped = Object.entries(entry.skipped)
      .sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0))
      .map(([reason, count]) => `${reason}: ${count}`)
      .join('; ')

    lines.push(
      `| \`${op}\` | ${entry.recorded} | ${entry.replayable} | ${skipped || '—'} | ${entry.readsClock ? 'yes' : ''} |`
    )
  }

  lines.push('', COUNTS_END)

  return lines.join('\n')
}

async function readmeWith(section: string): Promise<string> {
  const path = join(contractDir, 'README.md')
  const current = readFileSync(path, 'utf8')
  const start = current.indexOf(COUNTS_START)
  const end = current.indexOf(COUNTS_END)

  if (start < 0 || end < start) {
    throw new Error(`contract/README.md is missing the ${COUNTS_START} … ${COUNTS_END} markers`)
  }

  const text = `${current.slice(0, start)}${section}${current.slice(end + COUNTS_END.length)}`
  const options = (await prettier.resolveConfig(path)) ?? {}

  return prettier.format(text, { ...options, filepath: path })
}

async function main(): Promise<void> {
  const scratch = mkdtempSync(join(tmpdir(), 'hermie-golden-'))
  const out = join(scratch, 'contract')
  const statsDir = join(scratch, 'stats')

  try {
    mkdirSync(out, { recursive: true })

    step(
      'recording the transcript tests',
      'npx',
      ['vitest', 'run', '--config', 'packages/transcript/vitest.golden.config.ts', '--reporter=dot'],
      { GOLDEN_OUT: out, GOLDEN_STATS: statsDir }
    )
    step('dumping the transcript fixtures', 'npx', ['tsx', 'packages/transcript/golden/dump-fixtures.ts', '--out', out])
    step('dumping the gateway vectors', 'npx', ['tsx', 'packages/gateway-client/scripts/dump-vectors.ts', '--out', out])
    step('recording the stream scenarios', 'npx', ['tsx', 'packages/fake-gateway/scripts/dump-frames.ts', '--out', out])
    step('dumping the markdown blocks', 'npx', ['tsx', 'scripts/golden/dump-markdown.ts', '--out', out])

    const ops = aggregate(statsDir)
    const vectors: Record<string, number> = {}

    for (const file of filesUnder(join(out, 'gateway', 'vectors'))) {
      vectors[file] = (JSON.parse(readFileSync(join(out, 'gateway', 'vectors', file), 'utf8')) as unknown[]).length
    }

    const streams = filesUnder(join(out, 'transcript', 'streams')).length
    const markdown: Record<string, number> = {}

    for (const file of filesUnder(join(out, 'markdown'))) {
      markdown[file] = (JSON.parse(readFileSync(join(out, 'markdown', file), 'utf8')) as unknown[]).length
    }

    writeFileSync(join(out, 'transcript', 'golden-summary.json'), prettyJson({ operations: ops }))

    const readme = await readmeWith(countsSection(ops, streams, vectors, markdown))

    if (check) {
      const problems: string[] = []

      for (const owned of GENERATED) {
        const fresh = ownedFiles(out, owned)
        const committed = ownedFiles(contractDir, owned)

        for (const path of fresh) {
          if (!committed.includes(path)) {
            problems.push(`missing: contract/${path}`)
          } else if (!readFileSync(join(out, path)).equals(readFileSync(join(contractDir, path)))) {
            problems.push(`stale:   contract/${path}`)
          }
        }

        for (const path of committed) {
          if (!fresh.includes(path)) {
            problems.push(`extra:   contract/${path}`)
          }
        }
      }

      if (readme !== readFileSync(join(contractDir, 'README.md'), 'utf8')) {
        problems.push('stale:   contract/README.md (counts section)')
      }

      if (problems.length) {
        process.stderr.write(
          `The golden corpus is out of date with the TypeScript reference:\n  ${problems.slice(0, 40).join('\n  ')}\n` +
            `${problems.length > 40 ? `  … and ${problems.length - 40} more\n` : ''}` +
            'Run `npm run golden` and commit contract/ (and port the change to the native side).\n'
        )
        process.exit(1)
      }

      console.log('golden: contract/ is current.')

      return
    }

    for (const owned of GENERATED) {
      rmSync(join(contractDir, owned), { recursive: true, force: true })

      if (existsSync(join(out, owned))) {
        cpSync(join(out, owned), join(contractDir, owned), { recursive: true })
      }
    }

    writeFileSync(join(contractDir, 'README.md'), readme)
    console.log('golden: contract/ regenerated.')
  } finally {
    rmSync(scratch, { recursive: true, force: true })
  }
}

// Not a top-level await: the repository root is CommonJS, which tsx runs this as.
main().catch((error: unknown) => {
  console.error(error)
  process.exit(1)
})
