import Foundation
import Testing

@testable import HermieUI

/// One accessor call and what the TypeScript reference renders for it, per language.
/// `StringSamples` (generated by `npm run i18n`) holds one per key and argument combination.
struct StringSample: Sendable {
  let call: String
  let render: @Sendable () -> String
  let en: String
  let nl: String
  let de: String

  init(
    _ call: String, _ render: @escaping @Sendable () -> String, en: String, nl: String, de: String
  ) {
    self.call = call
    self.render = render
    self.en = en
    self.nl = nl
    self.de = de
  }

  func expected(in language: String) -> String {
    switch language {
    case "nl": nl
    case "de": de
    default: en
    }
  }
}

/// HermieUI's own resource bundle: the default the accessors look up in.
private let moduleBundle = HermieStringsLookup.bundle

/// One localization of the module bundle on its own, so a read lands in that language
/// whatever the machine running the tests is set to.
private func localization(_ language: String) throws -> Bundle {
  let path = try #require(moduleBundle.path(forResource: language, ofType: "lproj"))
  return try #require(Bundle(path: path))
}

/// Read `body` in `language`.
private func reading<T>(_ language: String, _ body: () throws -> T) throws -> T {
  try HermieStringsLookup.$bundle.withValue(try localization(language), operation: body)
}

@Test func theCatalogIsCompiledIntoTheModuleBundleInAllThreeLanguages() throws {
  #expect(Set(moduleBundle.localizations).isSuperset(of: ["en", "nl", "de"]))

  for language in ["en", "nl", "de"] {
    let bundle = try localization(language)
    #expect(bundle.path(forResource: "Localizable", ofType: "strings") != nil)
    #expect(bundle.path(forResource: "Localizable", ofType: "stringsdict") != nil)
  }
}

@Test func theDefaultLookupResolvesThroughTheModuleBundle() {
  // No language bound: whatever the system picks, a key resolves to text, never to itself.
  #expect(Strings.App.Common.cancel != "app.common.cancel")
  #expect(Strings.App.Bots.conversations(count: 2) != "app.bots.conversations")
}

@Test(arguments: ["en", "nl", "de"])
func everyKeyRendersWhatTheTypeScriptRenders(language: String) throws {
  var mismatches: [String] = []

  try reading(language) {
    for sample in StringSamples.all {
      let actual = sample.render()
      let expected = sample.expected(in: language)
      if actual != expected {
        mismatches.append("\(sample.call): \(actual.debugDescription) != \(expected.debugDescription)")
      }
    }
  }

  #expect(StringSamples.all.count > 2000)
  #expect(mismatches.isEmpty, "\(mismatches.count) of \(StringSamples.all.count) in \(language):\n\(mismatches.prefix(20).joined(separator: "\n"))")
}

@Test func plainInterpolatedAndPluralStringsReadAsTheyShould() throws {
  try reading("en") {
    #expect(Strings.App.Common.cancel == "Cancel")
    #expect(Strings.Chat.Context.percent(percent: 42) == "42%")
    #expect(Strings.App.Bots.conversations(count: 1) == "1 conversation")
    #expect(Strings.App.Bots.conversations(count: 0) == "0 conversations")
    #expect(Strings.Chat.Clarify.outcome(answered: 1, total: 3) == "Answered 1 of 3")
    #expect(Strings.Chat.Clarify.outcome(answered: 1, total: 1) == "Answered")
    #expect(
      Strings.App.Onboarding.Address.signInRequired(version: "", providers: ["GitHub", "Google", "Okta"])
        == "Hermes gateway · sign-in required via GitHub, Google or Okta")
  }

  try reading("nl") {
    #expect(Strings.App.Common.cancel == "Annuleren")
    #expect(Strings.App.Bots.conversations(count: 1) == "1 gesprek")
    #expect(Strings.App.Bots.conversations(count: 5) == "5 gesprekken")
    #expect(Strings.Chat.Clarify.outcome(answered: 3, total: 3) == "Alle 3 beantwoord")
    #expect(
      Strings.App.Onboarding.Address.signInRequired(version: "1.2", providers: ["GitHub", "Okta"])
        == "Hermes 1.2 · inloggen vereist via GitHub of Okta")
  }

  try reading("de") {
    #expect(Strings.App.Common.cancel == "Abbrechen")
    #expect(Strings.App.Bots.conversations(count: 1) == "1 Unterhaltung")
    #expect(Strings.App.Bots.conversations(count: 21) == "21 Unterhaltungen")
    #expect(Strings.Chat.Approval.eyebrow(handle: "ada") == "ZUGRIFFSANFRAGE · @ADA")
  }
}

@Test func aKeyedTableAnswersARuntimeKey() throws {
  try reading("nl") {
    #expect(Strings.Chat.Approval.Outcomes["once"] == "Eenmalig toegestaan")
    #expect(Strings.Chat.Approval.Outcomes["never-heard-of-it"] == nil)
  }
}

@Test func theNativeTableIsThereAndEmpty() {
  // `Native.xcstrings` holds strings only the native apps have; it starts empty, so a
  // lookup falls through to its key.
  #expect(String(localized: "native.placeholder", table: "Native", bundle: moduleBundle) == "native.placeholder")
}
