// Generated from packages/markdown/src/math/symbols.ts (the web and Expo clients' table), then kept by hand.
import Foundation

/// The LaTeX commands the renderer knows, as the characters they stand for. A table, not a font:
/// Unicode has every glyph a chat agent writes, and the platform face draws it.
///
/// A command that is not here makes the whole expression unrenderable and the block falls back to its
/// source: dropping an unknown command would silently change what the mathematics says.
enum MathSymbols {
  static let symbols: [String: String] = [
    "alpha": "α",
    "beta": "β",
    "gamma": "γ",
    "delta": "δ",
    "epsilon": "ε",
    "varepsilon": "ϵ",
    "zeta": "ζ",
    "eta": "η",
    "theta": "θ",
    "vartheta": "ϑ",
    "iota": "ι",
    "kappa": "κ",
    "lambda": "λ",
    "mu": "μ",
    "nu": "ν",
    "xi": "ξ",
    "pi": "π",
    "varpi": "ϖ",
    "rho": "ρ",
    "varrho": "ϱ",
    "sigma": "σ",
    "varsigma": "ς",
    "tau": "τ",
    "upsilon": "υ",
    "phi": "φ",
    "varphi": "ϕ",
    "chi": "χ",
    "psi": "ψ",
    "omega": "ω",
    "Gamma": "Γ",
    "Delta": "Δ",
    "Theta": "Θ",
    "Lambda": "Λ",
    "Xi": "Ξ",
    "Pi": "Π",
    "Sigma": "Σ",
    "Upsilon": "Υ",
    "Phi": "Φ",
    "Psi": "Ψ",
    "Omega": "Ω",
    "times": "×",
    "div": "÷",
    "pm": "±",
    "mp": "∓",
    "cdot": "·",
    "cdots": "⋯",
    "ldots": "…",
    "dots": "…",
    "vdots": "⋮",
    "ddots": "⋱",
    "ast": "∗",
    "star": "⋆",
    "circ": "∘",
    "bullet": "∙",
    "oplus": "⊕",
    "ominus": "⊖",
    "otimes": "⊗",
    "odot": "⊙",
    "le": "≤",
    "leq": "≤",
    "ge": "≥",
    "geq": "≥",
    "ne": "≠",
    "neq": "≠",
    "equiv": "≡",
    "approx": "≈",
    "sim": "∼",
    "simeq": "≃",
    "cong": "≅",
    "propto": "∝",
    "ll": "≪",
    "gg": "≫",
    "subset": "⊂",
    "subseteq": "⊆",
    "supset": "⊃",
    "supseteq": "⊇",
    "in": "∈",
    "notin": "∉",
    "ni": "∋",
    "cup": "∪",
    "cap": "∩",
    "setminus": "∖",
    "emptyset": "∅",
    "varnothing": "∅",
    "forall": "∀",
    "exists": "∃",
    "nexists": "∄",
    "neg": "¬",
    "lnot": "¬",
    "land": "∧",
    "wedge": "∧",
    "lor": "∨",
    "vee": "∨",
    "infty": "∞",
    "partial": "∂",
    "nabla": "∇",
    "angle": "∠",
    "perp": "⊥",
    "parallel": "∥",
    "therefore": "∴",
    "because": "∵",
    "degree": "°",
    "prime": "′",
    "hbar": "ℏ",
    "ell": "ℓ",
    "Re": "ℜ",
    "Im": "ℑ",
    "aleph": "ℵ",
    "to": "→",
    "rightarrow": "→",
    "Rightarrow": "⇒",
    "leftarrow": "←",
    "Leftarrow": "⇐",
    "leftrightarrow": "↔",
    "Leftrightarrow": "⇔",
    "longrightarrow": "⟶",
    "longleftarrow": "⟵",
    "mapsto": "↦",
    "uparrow": "↑",
    "downarrow": "↓",
    "implies": "⟹",
    "iff": "⟺"
  ]

  /// The big operators, which take limits above and below in display style.
  static let bigOperators: [String: String] = [
    "sum": "∑",
    "prod": "∏",
    "coprod": "∐",
    "int": "∫",
    "iint": "∬",
    "iiint": "∭",
    "oint": "∮",
    "bigcup": "⋃",
    "bigcap": "⋂",
    "bigoplus": "⨁",
    "bigotimes": "⨂",
    "bigvee": "⋁",
    "bigwedge": "⋀",
    "lim": "lim",
    "max": "max",
    "min": "min",
    "sup": "sup",
    "inf": "inf",
    "argmax": "arg max",
    "argmin": "arg min"
  ]

  /// The combining character each accent command draws.
  static let accents: [String: String] = [
    "hat": "\u{0302}",
    "bar": "\u{0304}",
    "vec": "\u{20D7}",
    "dot": "\u{0307}",
    "ddot": "\u{0308}",
    "tilde": "\u{0303}",
    "acute": "\u{0301}",
    "grave": "\u{0300}",
    "check": "\u{030C}",
    "breve": "\u{0306}",
    "overline": "\u{0304}"
  ]
}
