/**
 * The vectors the native clients check their port of the signature allowlist against:
 * `native/apple/HermieKit/Tests/Vectors/signature-svg.json`.
 *
 * Every entry is a file (its bytes, base64), the `mime` it is declared as, and what the fake gateway's own
 * `pngOrSvgProblem` says of it (`accepted`) and, for an SVG it refuses, the word of the first problem
 * (`word`, from `svgProblemWord`). The files are the ones `src/signature-svg-vectors.ts` holds for the vitest run
 * (what a pad draws, the refused elements, attributes and values), plus every attribute value of its table inside
 * a `<path>`, plus a few PNG heads. A native port must agree on `accepted` for every entry.
 *
 *   tsx packages/fake-gateway/scripts/dump-signature-svg-vectors.ts [--out <file>]
 */
import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

import { pngOrSvgProblem, svgProblemWord } from '../src/signature-svg'
import { SVG_ACCEPTED, SVG_ATTRIBUTE_VECTORS, SVG_REFUSED } from '../src/signature-svg-vectors'

const here = dirname(fileURLToPath(import.meta.url))
const argument = process.argv.indexOf('--out')
const out =
  argument === -1
    ? resolve(here, '../../../native/apple/HermieKit/Tests/Vectors/signature-svg.json')
    : resolve(process.argv[argument + 1] ?? '')

const NS = 'xmlns="http://www.w3.org/2000/svg"'
const bytes = (text: string): Uint8Array => new TextEncoder().encode(text)

interface Vector {
  name: string
  mime: string
  base64: string
  accepted: boolean
  word: string | null
}

const vectors: Vector[] = []

function add(name: string, mime: string, head: Uint8Array): void {
  const problem = pngOrSvgProblem(mime, head)

  vectors.push({
    name,
    mime,
    base64: Buffer.from(head).toString('base64'),
    accepted: problem === null,
    word: mime === 'image/svg+xml' && problem !== null ? svgProblemWord(head) : null
  })
}

for (const [name, text] of [...SVG_ACCEPTED, ...SVG_REFUSED]) {
  add(name, 'image/svg+xml', typeof text === 'string' ? bytes(text) : text)
}

for (const [attribute, value, expected] of SVG_ATTRIBUTE_VECTORS) {
  add(`${attribute}="${value}"`, 'image/svg+xml', bytes(`<svg ${NS}><path ${attribute}="${value}"/></svg>`))

  // The table says what the gateway should do; a regenerated file that disagrees is a bug in one of them.
  if (vectors[vectors.length - 1]?.accepted !== expected) {
    throw new Error(`The vector ${attribute}="${value}" is not read as the table says`)
  }
}

const signature = [0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]

add('a PNG head', 'image/png', Uint8Array.from([...signature, 1, 2, 3]))
add('a short PNG head', 'image/png', Uint8Array.from(signature.slice(0, 6)))
add('a GIF as a PNG', 'image/png', bytes('GIF89a'))
add('an empty PNG', 'image/png', new Uint8Array())
add('a JPEG', 'image/jpeg', Uint8Array.from([0xff, 0xd8, 0xff]))

mkdirSync(dirname(out), { recursive: true })
writeFileSync(
  out,
  `${JSON.stringify(
    {
      about:
        'Generated by packages/fake-gateway/scripts/dump-signature-svg-vectors.ts from the fake gateway (a port of the fork). Never edit by hand.',
      vectors
    },
    null,
    2
  )}\n`
)
console.log(`${vectors.length} vectors, ${vectors.filter(vector => vector.accepted).length} accepted → ${out}`)
