import ObjectiveC
import UIKit

/**
 Hermie's own menu in the Mac's menu bar, and the keyboard equivalents that go with it.

 A "Designed for iPad" app on macOS gets a menu bar whether it asks for one or not, built from
 UIKit's standard menus. Everything in it works — Edit ▸ Copy, Paste and Select All are
 `UIResponderStandardEditActions` that a `UITextView` implements, which is every `TextInput` in the
 app — but nothing in it is about Hermie. A Mac app has a menu for its own nouns, and the shortcuts
 in that menu are how the reader finds out the shortcuts exist at all.

 ## Why this is installed onto the app delegate's class at runtime

 `buildMenu(with:)` is a `UIResponder` method, and UIKit calls it on the APP DELEGATE. Hermie's app
 delegate is generated by the Expo SDK 54 template (`expo/hermie/ios` is not committed —
 CONTRIBUTING.md), and `ExpoAppDelegateSubscriber` has no menu hook to subscribe to, so there is no
 seam to write an override into. The scene delegate is not an alternative: a scene is in the
 responder chain but its DELEGATE is not.

 So the two methods are added to the app delegate's class with `class_addMethod`, from the module's
 `OnCreate`. Three things make that narrow rather than clever:

 - **It adds, it does not swizzle.** `UIResponder`'s own `buildMenu(with:)` does nothing, and
   nothing installed in this app implements it, so there is no previous behaviour to chain to.
   `class_addMethod` fails outright if the class already defines the method, which is the honest
   failure: `installed` goes false and there is no menu rather than a silently replaced one.
 - **The selector handler carries its meaning in the command.** `UIKeyCommand.propertyList` holds
   the same action id the keyboard path emits, so one JavaScript handler serves the menu bar and the
   keyboard, and there is no second table mapping selectors to intentions.
 - **Titles come from JavaScript.** The app's strings live in `src/i18n/strings.ts` and a menu bar
   spelled in Swift would be a second, untranslated copy. `setMenuBar` hands them over and asks
   UIKit to rebuild; until it is called there is no Hermie menu, which is also what a Release build
   that never reaches the chat list should show.

 ## The one standard item it takes away

 `UIMenu.Identifier.close` — the window's ⌘W — is removed and replaced with an item of Hermie's own.
 The owner asked for ⌘W to close the overlay or sheet, one level, the way Escape does; with the
 standard item in place the keystroke never reaches the app, it closes the window. Replacing it
 rather than merely removing it keeps a Close line in the menu bar, so the shortcut is still
 discoverable and still says what it does.

 **Not verified at runtime.** The Mac cannot be launched from here (ADR-0011: the build is scripted,
 the run needs a window). What is checked is that the symbols are in the built binary, and that the
 JavaScript side of it is unit tested. `docs/platform-notes.md` tracks the difference.
 */
@objc public final class HermieMenuBar: NSObject {
  /// What a menu selection or a shortcut should do, handed back to JavaScript by the module.
  public static var onCommand: ((String) -> Void)?

  private static var titles: [String: String] = [:]
  private static var chats: [String] = []
  private static var installed = false

  /// Everything Hermie adds lives under one identifier, so a rebuild replaces rather than repeats.
  private static let menuIdentifier = UIMenu.Identifier("dev.hermie.menu.chats")

  /**
   Teach the app delegate's class to build a menu and to run a command.

   Idempotent, and safe to call before any menu exists: UIKit will call `buildMenu(with:)` when it
   is ready, and `setMenuBar` asks for a rebuild once JavaScript has the strings.
   */
  @objc public static func install() {
    guard !installed, let delegate = UIApplication.shared.delegate else {
      return
    }

    let delegateClass: AnyClass = type(of: delegate)

    let build: @convention(block) (AnyObject, AnyObject) -> Void = { _, builder in
      guard let builder = builder as? UIMenuBuilder else {
        return
      }

      HermieMenuBar.build(with: builder)
    }

    let run: @convention(block) (AnyObject, AnyObject?) -> Void = { _, sender in
      guard let id = (sender as? UIKeyCommand)?.propertyList as? String else {
        return
      }

      HermieMenuBar.onCommand?(id)
    }

    let addedBuild = class_addMethod(
      delegateClass,
      #selector(UIResponder.buildMenu(with:)),
      imp_implementationWithBlock(build),
      "v@:@"
    )

    let addedRun = class_addMethod(
      delegateClass,
      #selector(HermieMenuBar.hermieMenuCommand(_:)),
      imp_implementationWithBlock(run),
      "v@:@"
    )

    installed = addedBuild && addedRun
  }

  /**
   The strings, from JavaScript, and a rebuild.

   `chats` is the visible chat list in its own order, capped at nine by the shortcuts it gets. An
   empty dictionary is a legitimate call: it clears the menu, which is what signing out should do.
   */
  @objc public static func setMenuBar(titles: [String: String], chats: [String]) {
    self.titles = titles
    self.chats = Array(chats.prefix(9))

    // Tried again here as well as from `OnCreate`: a module is created while the app delegate is
    // still inside `didFinishLaunching`, and a delegate that was not yet set then would otherwise
    // leave the menu permanently uninstalled.
    install()

    guard installed else {
      return
    }

    // A rebuild touches the menu bar, which is UIKit state.
    if Thread.isMainThread {
      UIMenuSystem.main.setNeedsRebuild()
    } else {
      DispatchQueue.main.async { UIMenuSystem.main.setNeedsRebuild() }
    }
  }

  /// Whether both methods reached the app delegate's class. Reported on the developer screen.
  @objc public static var isInstalled: Bool { installed }

  /// The selector the menu items are bound to; never called through this class.
  @objc public func hermieMenuCommand(_ sender: Any?) {}

  private static func build(with builder: UIMenuBuilder) {
    guard let chatsTitle = titles["chats"] else {
      // No strings yet: leave the standard menu bar exactly as UIKit built it.
      return
    }

    // Replaced rather than removed — see the class comment. Order matters: the standard item has to
    // go before ours claims the same key equivalent.
    builder.remove(menu: .close)

    var commands: [UIMenuElement] = []

    if let search = titles["search"] {
      commands.append(command(title: search, key: "k", id: "search"))
    }

    if let settings = titles["settings"] {
      commands.append(command(title: settings, key: ",", id: "settings"))
    }

    if let close = titles["close"] {
      commands.append(command(title: close, key: "w", id: "close"))
    }

    // ⌘N is "new conversation in the chat that is open", which is what a Mac reader expects ⌘N to
    // mean in a window showing one conversation. It runs the app's own `/new`; see
    // `src/platform/desktop-shortcuts.shared.ts`, where the chord is decided.
    if let newConversation = titles["newConversation"] {
      commands.append(command(title: newConversation, key: "n", id: "newConversation"))
    }

    // The one item whose TITLE is state. JavaScript sends "Hide Sidebar" or "Show Sidebar" already
    // resolved, because whether the sidebar is showing is a question about a window width and a
    // stored preference, and neither of those is knowable from here.
    if let toggleSidebar = titles["toggleSidebar"] {
      commands.append(
        command(title: toggleSidebar, key: "s", id: "toggleSidebar", modifiers: [.command, .shift])
      )
    }

    let numbered = chats.enumerated().map { index, name in
      command(title: name, key: String(index + 1), id: "chat\(index + 1)")
    }

    var children: [UIMenuElement] = []

    if !commands.isEmpty {
      children.append(UIMenu(title: "", options: .displayInline, children: commands))
    }

    if !numbered.isEmpty {
      children.append(UIMenu(title: "", options: .displayInline, children: numbered))
    }

    guard !children.isEmpty else {
      return
    }

    builder.insertSibling(
      UIMenu(title: chatsTitle, identifier: menuIdentifier, children: children),
      afterMenu: .view
    )
  }

  private static func command(
    title: String,
    key: String,
    id: String,
    modifiers: UIKeyModifierFlags = .command
  ) -> UIKeyCommand {
    UIKeyCommand(
      title: title,
      action: #selector(HermieMenuBar.hermieMenuCommand(_:)),
      input: key,
      modifierFlags: modifiers,
      propertyList: id
    )
  }
}
